"""T088 decision_price on signal_log

Revision ID: 00c4e1efd5c4
Revises: 69a772af165c
Create Date: 2026-08-14 23:00:11.612694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '00c4e1efd5c4'
down_revision: Union[str, None] = '69a772af165c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_log', sa.Column('decision_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal_log', 'decision_price')
    # ### end Alembic commands ###
