"""T064 promotion_status

Revision ID: 04e68aa1c90a
Revises: 080e1c184167
Create Date: 2026-08-13 23:32:55.574088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '04e68aa1c90a'
down_revision: Union[str, None] = '080e1c184167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('promotion_status', sa.String(length=24), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_runs', 'promotion_status')
    # ### end Alembic commands ###
