"""T063 decision journal

Revision ID: 080e1c184167
Revises: 08dfc64f8e4b
Create Date: 2026-08-13 23:17:00.008543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '080e1c184167'
down_revision: Union[str, None] = '08dfc64f8e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('thesis', sa.String(length=1000), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('key_risk', sa.String(length=500), nullable=True),
    sa.Column('regime', sa.String(length=24), nullable=True),
    sa.Column('regime_confidence', sa.Float(), nullable=True),
    sa.Column('followed', sa.Boolean(), nullable=True),
    sa.Column('follow_note', sa.String(length=500), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journal_symbol_ts', 'decision_journal', ['symbol', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_journal_symbol_ts', table_name='decision_journal')
    op.drop_table('decision_journal')
    # ### end Alembic commands ###
