"""investment_policy table

Revision ID: 08dfc64f8e4b
Revises: 5b54677a6d1d
Create Date: 2026-08-11 23:31:42.283450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '08dfc64f8e4b'
down_revision: Union[str, None] = '5b54677a6d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objectives', sa.String(length=500), nullable=True),
    sa.Column('target_annual_return_frac', sa.Float(), nullable=True),
    sa.Column('max_drawdown_frac', sa.Float(), nullable=True),
    sa.Column('horizon_years', sa.Float(), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=32), nullable=True),
    sa.Column('restrictions_json', sa.String(length=2000), nullable=False),
    sa.Column('prohibited_strategies_json', sa.String(length=2000), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment_policy')
    # ### end Alembic commands ###
