"""backtest_runs table

Revision ID: 33592ebf6de6
Revises: 35b6c01bf49b
Create Date: 2026-08-11 16:02:01.237487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '33592ebf6de6'
down_revision: Union[str, None] = '35b6c01bf49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strategy', sa.String(length=48), nullable=False),
    sa.Column('params_json', sa.String(length=512), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('bars_count', sa.Integer(), nullable=False),
    sa.Column('cost_bps', sa.Float(), nullable=False),
    sa.Column('cumulative_return', sa.Float(), nullable=False),
    sa.Column('volatility_ann', sa.Float(), nullable=True),
    sa.Column('sharpe_ann', sa.Float(), nullable=True),
    sa.Column('max_drawdown_frac', sa.Float(), nullable=False),
    sa.Column('n_rebalances', sa.Integer(), nullable=False),
    sa.Column('total_cost_frac', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_symbol'), 'backtest_runs', ['symbol'], unique=False)
    op.create_index('ix_backtest_strategy_ts', 'backtest_runs', ['strategy', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backtest_strategy_ts', table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_symbol'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
