"""risk_state table

Revision ID: 35b6c01bf49b
Revises: c09d9671853d
Create Date: 2026-08-11 15:50:35.048370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '35b6c01bf49b'
down_revision: Union[str, None] = 'c09d9671853d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=True),
    sa.Column('day_start_equity', sa.Float(), nullable=True),
    sa.Column('tripped', sa.Boolean(), nullable=False),
    sa.Column('trip_reason', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_state')
    # ### end Alembic commands ###
