"""risk_state lockout_until

Revision ID: 5b54677a6d1d
Revises: 7bb8528ec2d3
Create Date: 2026-08-11 23:15:41.796550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5b54677a6d1d'
down_revision: Union[str, None] = '7bb8528ec2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_state', sa.Column('lockout_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_state', 'lockout_until')
    # ### end Alembic commands ###
