"""T068 watchlist table

Revision ID: 620eeac1a7c9
Revises: 8d2d7f6c98b8
Create Date: 2026-08-14 20:21:09.152668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '620eeac1a7c9'
down_revision: Union[str, None] = '8d2d7f6c98b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('added_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_symbol'), 'watchlist', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_symbol'), table_name='watchlist')
    op.drop_table('watchlist')
    # ### end Alembic commands ###
