"""T060 cash_flows table

Revision ID: 69a772af165c
Revises: 620eeac1a7c9
Create Date: 2026-08-14 22:55:22.692127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69a772af165c'
down_revision: Union[str, None] = '620eeac1a7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['broker_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'external_id', name='uq_cashflow_external')
    )
    op.create_index(op.f('ix_cash_flows_account_id'), 'cash_flows', ['account_id'], unique=False)
    op.create_index(op.f('ix_cash_flows_occurred_at'), 'cash_flows', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_flows_occurred_at'), table_name='cash_flows')
    op.drop_index(op.f('ix_cash_flows_account_id'), table_name='cash_flows')
    op.drop_table('cash_flows')
    # ### end Alembic commands ###
