"""T091 transaction order_id

Revision ID: 89e88db0d156
Revises: f71b527814ef
Create Date: 2026-08-14 00:25:35.421002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '89e88db0d156'
down_revision: Union[str, None] = 'f71b527814ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('order_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_transactions_order_id'), 'transactions', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_order_id'), table_name='transactions')
    op.drop_column('transactions', 'order_id')
    # ### end Alembic commands ###
