"""T092 stability_json on backtest_runs

Revision ID: 8d2d7f6c98b8
Revises: 89e88db0d156
Create Date: 2026-08-14 15:34:13.697159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d2d7f6c98b8'
down_revision: Union[str, None] = '89e88db0d156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('stability_json', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_runs', 'stability_json')
    # ### end Alembic commands ###
