"""signal_log table

Revision ID: c09d9671853d
Revises: bee2b4896cdf
Create Date: 2026-08-11 15:41:32.937662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c09d9671853d'
down_revision: Union[str, None] = 'bee2b4896cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strategy', sa.String(length=48), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('signal_weight', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('reasons', sa.String(length=1024), nullable=True),
    sa.Column('order_external_id', sa.String(length=64), nullable=True),
    sa.Column('bars_asof', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_symbol_ts', 'signal_log', ['symbol', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signal_symbol_ts', table_name='signal_log')
    op.drop_table('signal_log')
    # ### end Alembic commands ###
