"""T091 attribution tags

Revision ID: f71b527814ef
Revises: 04e68aa1c90a
Create Date: 2026-08-14 00:23:52.299309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f71b527814ef'
down_revision: Union[str, None] = '04e68aa1c90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_log', sa.Column('regime_label', sa.String(length=24), nullable=True))
    op.add_column('signal_log', sa.Column('sub_strategy', sa.String(length=48), nullable=True))
    op.add_column('signal_log', sa.Column('entry_bucket', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal_log', 'entry_bucket')
    op.drop_column('signal_log', 'sub_strategy')
    op.drop_column('signal_log', 'regime_label')
    # ### end Alembic commands ###
